project_id = "iwyntbeqdvsbzvmskpaw"

[functions.analyze-text]
verify_jwt = false

[functions.analyze-image]
verify_jwt = false

[functions.analyze-video]
verify_jwt = false

[functions.moderation-feedback]
verify_jwt = false